package com.PennList;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.PennList.Listing;

import com.PennList.ListingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig listingDaoConfig;

    private final ListingDao listingDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        listingDaoConfig = daoConfigMap.get(ListingDao.class).clone();
        listingDaoConfig.initIdentityScope(type);

        listingDao = new ListingDao(listingDaoConfig, this);

        registerDao(Listing.class, listingDao);
    }
    
    public void clear() {
        listingDaoConfig.getIdentityScope().clear();
    }

    public ListingDao getListingDao() {
        return listingDao;
    }

}
